I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 462, in script
    h1 "「너.. [playername] 맞아?」"
Exception: Sayer 'hl' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 462, in script
    h1 "「너.. [playername] 맞아?」"
  File "C:\Users\김학인\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\김학인\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'hl' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
prototype 1.0
Sun Nov 08 18:32:22 2020
